"use strict";

export const ELEMENT = {
  A: "a",
  ARTICLE: "article",
  DIV: "div",
  FOOTER: "footer",
  H1: "h1",
  H2: "h2",
  H3: "h3",
  H4: "h4",
  H5: "h5",
  HEADER: "header",
  IFRAME: "iframe",
  IMG: "img",
  LABEL: "label",
  LI: "li",
  P: "p",
  SECTION: "section",
  SPAN: "span",
  TABLE: "table",
  TBODY: "tbody",
  TD: "td",
  TEMPLATE: "template",
  TH: "th",
  THEAD: "thead",
  TR: "tr",
  UL: "ul",
  VIDEO: "video",
};
