"use strict";

export const EVENT = {
  ABORT: "abort",
  BLUR: "blur",
  CHANGE: "change",
  CLICK: "click",
  COMPLETE: "complete",
  DRAG: "drag",
  DRAG_END: "dragend",
  DRAG_ENTER: "dragenter",
  DRAG_LEAVE: "dragleave",
  DRAG_OVER: "dragover",
  DRAG_START: "dragstart",
  DROP: "drop",
  ERROR: "error",
  FOCUS: "focus",
  KEY_DOWN: "keydown",
  KEY_UP: "keyup",
  LOAD: "load",
  LOAD_END: "loadend",
  MOUSE_DOWN: "mousedown",
  POP_STATE: "popstate",
  PROGRESS: "progress",
  SUBMIT: "submit",
  SUCCESS: "success",
  TOUCH_CANCEL: "touchcancel",
  TOUCH_END: "touchend",
  TOUCH_MOVE: "touchmove",
  TOUCH_START: "touchstart",
  UPGRADE_NEEDED: "upgradeneeded",
};
